<?php

namespace Database\Seeders;

use App\Models\PageContent;
use Illuminate\Database\Seeder;

class PageContentSeeder extends Seeder
{
    public function run(): void
    {
        PageContent::truncate();

        $contents = [
            // HOME PAGE
            [
                'page_key' => 'home',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner Principal (Hero)',
                'type' => 'text',
                'value' => 'Desenvolvendo Soluções Sustentáveis para Angola',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'hero',
                'content_key' => 'hero_subtitle',
                'label' => 'Subtítulo do Banner Principal (Hero)',
                'type' => 'textarea',
                'value' => 'O ABP Group lidera a engenharia civil, climatização, apoio petrolífero e gestão ambiental, promovendo um crescimento integrado com impacto local.',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'intro',
                'content_key' => 'intro_label',
                'label' => 'Secção Introdução - Rótulo/Etiqueta (Vermelho)',
                'type' => 'text',
                'value' => 'O NOSSO GRUPO',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'intro',
                'content_key' => 'intro_title',
                'label' => 'Título da Secção de Introdução',
                'type' => 'text',
                'value' => 'O Nosso Compromisso',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'intro',
                'content_key' => 'intro_text',
                'label' => 'Texto da Secção de Introdução',
                'type' => 'textarea',
                'value' => 'Com mais de 10 anos de experiência em Angola, actuamos em sectores altamente estratégicos fornecendo engenharia de topo e responsabilidade ambiental.',
            ],

            [
                'page_key' => 'about',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner',
                'type' => 'text',
                'value' => 'Sobre o ABP Group',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'body',
                'content_key' => 'intro_title',
                'label' => 'Título da Introdução (Suporta HTML para quebras e cores)',
                'type' => 'textarea',
                'value' => 'Construímos soluções<br />que impulsionam o crescimento<br />e o <span class="text-[#cc1f26]">desenvolvimento sustentável</span>',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'body',
                'content_key' => 'intro_text',
                'label' => 'Texto de Introdução',
                'type' => 'textarea',
                'value' => 'O ABP Group é um grupo empresarial angolano que actua em sectores estratégicos da economia, oferecendo soluções especializadas nas áreas de energia, engenharia, construção, gestão de infraestruturas, saúde e sustentabilidade.',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'body',
                'content_key' => 'team_image',
                'label' => 'Imagem da Equipa (Meio da Página)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'body',
                'content_key' => 'legacy_text_1',
                'label' => 'Parágrafo do Histórico/Legado 1',
                'type' => 'textarea',
                'value' => 'Ao longo da nossa trajectória, consolidámos uma posição de referência através da prestação de serviços especializados e da capacidade de responder aos desafios dos sectores mais exigentes. Acreditamos que o sucesso sustentável é construído através da qualidade, da confiança e da criação de soluções que geram impacto positivo.',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'body',
                'content_key' => 'legacy_text_2',
                'label' => 'Parágrafo do Histórico/Legado 2',
                'type' => 'textarea',
                'value' => 'Com uma abordagem integrada e uma equipa multidisciplinar, desenvolvemos projectos que combinam conhecimento técnico, inovação e excelência operacional. O nosso compromisso é criar valor duradouro para clientes, parceiros e comunidades, contribuindo activamente para o desenvolvimento económico e social de Angola.',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'missao_visao_valores',
                'content_key' => 'mission_text',
                'label' => 'Texto da Missão',
                'type' => 'textarea',
                'value' => 'Contribuir para o desenvolvimento sustentável de Angola através da prestação de serviços especializados e soluções integradas, criando valor para clientes, parceiros e comunidades com elevados padrões de qualidade, segurança e excelência operacional.',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'missao_visao_valores',
                'content_key' => 'vision_text',
                'label' => 'Texto da Visão',
                'type' => 'textarea',
                'value' => 'Ser a referência em Angola na entrega de soluções inovadoras de engenharia, construção e sustentabilidade, promovendo parcerias sólidas de longo prazo.',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'missao_visao_valores',
                'content_key' => 'values_text',
                'label' => 'Texto dos Valores',
                'type' => 'textarea',
                'value' => 'Os nossos valores orientam cada decisão e cada projecto que desenvolvemos. Acreditamos na excelência, na integridade, na inovação e na segurança como pilares fundamentais para construir relações de confiança e gerar impacto positivo e sustentável.',
            ],
            // ABOUT STATS
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat1_number',
                'label' => 'Estatística 1 - Valor/Número',
                'type' => 'text',
                'value' => '150',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat1_suffix',
                'label' => 'Estatística 1 - Sufixo (ex: +)',
                'type' => 'text',
                'value' => '+',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat1_label',
                'label' => 'Estatística 1 - Legenda',
                'type' => 'text',
                'value' => 'Projetos Concluídos',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat2_number',
                'label' => 'Estatística 2 - Valor/Número',
                'type' => 'text',
                'value' => '450',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat2_suffix',
                'label' => 'Estatística 2 - Sufixo (ex: +)',
                'type' => 'text',
                'value' => '+',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat2_label',
                'label' => 'Estatística 2 - Legenda',
                'type' => 'text',
                'value' => 'Colaboradores Diretos',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat3_number',
                'label' => 'Estatística 3 - Valor/Número',
                'type' => 'text',
                'value' => '4',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat3_suffix',
                'label' => 'Estatística 3 - Sufixo',
                'type' => 'text',
                'value' => '',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat3_label',
                'label' => 'Estatística 3 - Legenda',
                'type' => 'text',
                'value' => 'Áreas de Negócio',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat4_number',
                'label' => 'Estatística 4 - Valor/Número',
                'type' => 'text',
                'value' => '15',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat4_suffix',
                'label' => 'Estatística 4 - Sufixo (ex: +)',
                'type' => 'text',
                'value' => '+',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat4_label',
                'label' => 'Estatística 4 - Legenda',
                'type' => 'text',
                'value' => 'Anos de Experiência',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat5_number',
                'label' => 'Estatística 5 - Valor/Número',
                'type' => 'text',
                'value' => '18',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat5_suffix',
                'label' => 'Estatística 5 - Sufixo',
                'type' => 'text',
                'value' => '',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat5_label',
                'label' => 'Estatística 5 - Legenda',
                'type' => 'text',
                'value' => 'Províncias Alcançadas',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat6_number',
                'label' => 'Estatística 6 - Valor/Número',
                'type' => 'text',
                'value' => '100',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat6_suffix',
                'label' => 'Estatística 6 - Sufixo (ex: %)',
                'type' => 'text',
                'value' => '%',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat6_label',
                'label' => 'Estatística 6 - Legenda',
                'type' => 'text',
                'value' => 'Cumprimento e Segurança',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat7_number',
                'label' => 'Estatística 7 - Valor/Número',
                'type' => 'text',
                'value' => '20',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat7_suffix',
                'label' => 'Estatística 7 - Sufixo (ex: +)',
                'type' => 'text',
                'value' => '+',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat7_label',
                'label' => 'Estatística 7 - Legenda',
                'type' => 'text',
                'value' => 'Parceiros Estratégicos',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat8_number',
                'label' => 'Estatística 8 - Valor/Número',
                'type' => 'text',
                'value' => '50',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat8_suffix',
                'label' => 'Estatística 8 - Sufixo (ex: k)',
                'type' => 'text',
                'value' => 'k',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'stats',
                'content_key' => 'stat8_label',
                'label' => 'Estatística 8 - Legenda',
                'type' => 'text',
                'value' => 'Horas de Formação',
            ],
            // ABOUT DIRECTOR MESSAGE
            [
                'page_key' => 'about',
                'section_key' => 'director_message',
                'content_key' => 'director_image',
                'label' => 'Mensagem do Diretor - Imagem do PCA',
                'type' => 'image',
                'value' => 'images/abp_ceo.webp',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'director_message',
                'content_key' => 'director_title',
                'label' => 'Mensagem do Diretor - Título',
                'type' => 'text',
                'value' => 'Compromisso com a Excelência e Sustentabilidade em Angola',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'director_message',
                'content_key' => 'director_text_1',
                'label' => 'Mensagem do Diretor - Parágrafo 1',
                'type' => 'textarea',
                'value' => 'A nossa trajectória é marcada por uma procura incessante de soluções que combinam conhecimento técnico com as melhores práticas internacionais. Ao longo dos anos, o ABP Group solidificou a sua presença através de um crescimento estratégico, apoiado numa equipa extraordinária e na confiança dos nossos parceiros.',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'director_message',
                'content_key' => 'director_text_2',
                'label' => 'Mensagem do Diretor - Parágrafo 2',
                'type' => 'textarea',
                'value' => 'O nosso maior orgulho não são apenas os projectos que entregamos, mas o impacto positivo e duradouro que deixamos nas comunidades. Continuaremos a liderar com integridade e inovação para o futuro do nosso país.',
            ],
            // ABOUT CORPORATE VIDEO
            [
                'page_key' => 'about',
                'section_key' => 'corporate_video',
                'content_key' => 'director_video',
                'label' => 'Vídeo Corporativo (Ficheiro de Vídeo)',
                'type' => 'video',
                'value' => 'hero_video.mp4',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'corporate_video',
                'content_key' => 'director_video_poster',
                'label' => 'Vídeo Corporativo - Capa/Poster (Imagem)',
                'type' => 'image',
                'value' => 'images/home-hero-new.png',
            ],


            // SERVICES PAGE
            [
                'page_key' => 'services',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner',
                'type' => 'text',
                'value' => 'Serviços e Soluções Integradas',
            ],

            // CONTACT PAGE
            [
                'page_key' => 'contact',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner',
                'type' => 'text',
                'value' => 'Contacte-nos',
            ],

            // PANTHERBUILD PAGE
            [
                'page_key' => 'panther-build',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner',
                'type' => 'text',
                'value' => 'PantherBUILD',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'body',
                'content_key' => 'description',
                'label' => 'Descrição Principal do Serviço (Parágrafo 1)',
                'type' => 'textarea',
                'value' => 'A PantherBUILD é a nossa marca dedicada ao sector da construção civil. Desenvolvemos projectos industriais de raiz, requalificações urbanas e naves de logística.',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'body',
                'content_key' => 'intro_title',
                'label' => 'Título de Introdução (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Construção Civil, Engenharia e <span class="text-[#dd5209] font-extrabold block mb-2">estruturas duradouras</span>',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'body',
                'content_key' => 'description_2',
                'label' => 'Descrição Principal do Serviço (Parágrafo 2)',
                'type' => 'textarea',
                'value' => 'A nossa equipa de engenheiros civis e fiscais de obra alia metodologias construtivas modernas de betão e estruturas metálicas a um forte sentido de responsabilidade civil e segurança laboral nos estaleiros.',
            ],
            // PANTHERBUILD HIGHLIGHT BOX
            [
                'page_key' => 'panther-build',
                'section_key' => 'destaque_laranja',
                'content_key' => 'overlay_image',
                'label' => 'Imagem de Fundo do Destaque',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'destaque_laranja',
                'content_key' => 'overlay_title',
                'label' => 'Título da Caixa Laranja',
                'type' => 'text',
                'value' => 'Edificar Angola',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'destaque_laranja',
                'content_key' => 'overlay_text_1',
                'label' => 'Texto da Caixa Laranja - Parágrafo 1',
                'type' => 'textarea',
                'value' => 'A PantherBUILD destaca-se pela sua capacidade técnica superior, assegurando que cada projeto cumpra rigorosos padrões internacionais de qualidade e segurança no trabalho.',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'destaque_laranja',
                'content_key' => 'overlay_text_2',
                'label' => 'Texto da Caixa Laranja - Parágrafo 2',
                'type' => 'textarea',
                'value' => 'Temos uma visão de longo prazo orientada para o desenvolvimento das infraestruturas essenciais do país.',
            ],
            // PANTHERBUILD SERVICE CARDS
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card1_image',
                'label' => 'Cartão 1 - Imagem',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1587582423116-ec07293f0395?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card1_title',
                'label' => 'Cartão 1 - Título',
                'type' => 'text',
                'value' => 'Construção Industrial',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card1_text',
                'label' => 'Cartão 1 - Descrição',
                'type' => 'textarea',
                'value' => 'Edificação de pavilhões metálicos, centros de logística e armazéns.',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card2_image',
                'label' => 'Cartão 2 - Imagem',
                'type' => 'image',
                'value' => 'https://www.simplybusiness.co.uk/wp-content/uploads/sites/3/2024/05/2024-predictions-for-tradespeople.jpeg',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card2_title',
                'label' => 'Cartão 2 - Título',
                'type' => 'text',
                'value' => 'Obras Públicas',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card2_text',
                'label' => 'Cartão 2 - Descrição',
                'type' => 'textarea',
                'value' => 'Reabilitação de vias urbanas, terraplenagem e saneamento integrado.',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card3_image',
                'label' => 'Cartão 3 - Imagem',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card3_title',
                'label' => 'Cartão 3 - Título',
                'type' => 'text',
                'value' => 'Fiscalização e Design',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card3_text',
                'label' => 'Cartão 3 - Descrição',
                'type' => 'textarea',
                'value' => 'Elaboração de plantas de cálculo de betão armado e coordenação de obra.',
            ],
            // PANTHERBUILD ENGENHARIA MODERNA
            [
                'page_key' => 'panther-build',
                'section_key' => 'engenharia_moderna',
                'content_key' => 'modern_image',
                'label' => 'Engenharia Moderna - Imagem Lateral',
                'type' => 'image',
                'value' => 'https://img.magnific.com/free-photo/african-american-worker-standing-uniform-wearing-safety-hat-factory_1303-30606.jpg',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'engenharia_moderna',
                'content_key' => 'modern_title',
                'label' => 'Engenharia Moderna - Título (Suporta HTML)',
                'type' => 'textarea',
                'value' => '<span class="text-[#1c3986] block">Engenharia Moderna</span><span class="text-[#dd5209] font-extrabold  block">e Estruturas Avançadas</span>',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'engenharia_moderna',
                'content_key' => 'modern_text_1',
                'label' => 'Engenharia Moderna - Parágrafo 1',
                'type' => 'textarea',
                'value' => 'Desempenhamos um papel fulcral na modernização de complexos industriais, garantindo elevados padrões de qualidade na execução de cada etapa de engenharia civil.',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'engenharia_moderna',
                'content_key' => 'modern_text_2',
                'label' => 'Engenharia Moderna - Parágrafo 2',
                'type' => 'textarea',
                'value' => 'A nossa missão foca-se na eficiência estrutural e segurança ambiental de todos os estaleiros.',
            ],
            // PANTHERBUILD NOSSOS PROJECTOS
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'projects_title',
                'label' => 'Nossos Projectos - Título (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Projectos que reflectem a nossa <br /><span class="text-[#dd5209]">experiência, qualidade e compromisso</span>',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'projects_subtitle',
                'label' => 'Nossos Projectos - Subtítulo',
                'type' => 'textarea',
                'value' => 'Conheça em detalhe algumas das nossas obras estruturais de referência desenvolvidas para clientes nacionais e internacionais.',
            ],
            // Project 1
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project1_image',
                'label' => 'Projecto 1 - Imagem (Centro Logístico)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project1_title',
                'label' => 'Projecto 1 - Título',
                'type' => 'text',
                'value' => 'Centro Logístico de Talatona',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project1_category',
                'label' => 'Projecto 1 - Categoria/Subtítulo',
                'type' => 'text',
                'value' => 'Construção Industrial',
            ],
            // Project 2
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project2_image',
                'label' => 'Projecto 2 - Imagem (Pavilhão)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1531834685032-c34bf0d84c77?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project2_title',
                'label' => 'Projecto 2 - Título',
                'type' => 'text',
                'value' => 'Pavilhão de Armazenamento',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project2_category',
                'label' => 'Projecto 2 - Categoria/Subtítulo',
                'type' => 'text',
                'value' => 'Estrutura Metálica',
            ],
            // Project 3
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project3_image',
                'label' => 'Projecto 3 - Imagem (Urbanização)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1587582423116-ec07293f0395?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project3_title',
                'label' => 'Projecto 3 - Título',
                'type' => 'text',
                'value' => 'Urbanização de Vias',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project3_category',
                'label' => 'Projecto 3 - Categoria/Subtítulo',
                'type' => 'text',
                'value' => 'Infraestrutura rodoviária',
            ],
            // Project 4
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project4_image',
                'label' => 'Projecto 4 - Imagem (Engenharia Civil)',
                'type' => 'image',
                'value' => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjNw9NAzytNyKhAZRBOhwdvxMGeX19g3DfF2g23VaXn8GnoWe16tuLsyhvWyg3o4DrJHNmcfN6KNsWwIuK0aJadYncw0S81J-mNpq_E_mWknNTuR_Xx-VZY5roGVDwZToI2x0S_Qqyfm4KR/s1600/MDA.jpg',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project4_title',
                'label' => 'Projecto 4 - Título',
                'type' => 'text',
                'value' => 'Engenharia Civil',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project4_category',
                'label' => 'Projecto 4 - Categoria/Subtítulo',
                'type' => 'text',
                'value' => 'Obras Públicas',
            ],
            // Project 5
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project5_image',
                'label' => 'Projecto 5 - Imagem (Auditoria)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project5_title',
                'label' => 'Projecto 5 - Título',
                'type' => 'text',
                'value' => 'Auditoria Técnica',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'nossos_projectos',
                'content_key' => 'project5_category',
                'label' => 'Projecto 5 - Categoria/Subtítulo',
                'type' => 'text',
                'value' => 'Controlo de Qualidade',
            ],

            // PANTHERMAT PAGE
            [
                'page_key' => 'panther-mat',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner',
                'type' => 'text',
                'value' => 'PantherMAT',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'body',
                'content_key' => 'description',
                'label' => 'Descrição Principal do Serviço (Parágrafo 1)',
                'type' => 'textarea',
                'value' => 'A PantherMAT actua na instalação, manutenção e assistência técnica de equipamentos de AVAC e distribuição de fluidos industriais para edifícios corporativos.',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'body',
                'content_key' => 'intro_title',
                'label' => 'Título de Introdução (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Soluções de gestão e manutenção que <span class="text-gray-600 font-extrabold"> garantem continuidade operacional</span>',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'body',
                'content_key' => 'description_2',
                'label' => 'Descrição Principal do Serviço (Parágrafo 2)',
                'type' => 'textarea',
                'value' => 'A nossa equipa técnica de engenheiros e mecânicos credenciados assegura que equipamentos críticos de refrigeração e eletricidade funcionem sem interrupções indesejadas, prolongando a vida útil dos seus ativos físicos.',
            ],
            // BANNER DESTAQUE GRANDE
            [
                'page_key' => 'panther-mat',
                'section_key' => 'banner_destaque',
                'content_key' => 'banner_image',
                'label' => 'Imagem de Fundo do Banner Grande',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'banner_destaque',
                'content_key' => 'banner_title',
                'label' => 'Título do Banner Grande',
                'type' => 'textarea',
                'value' => 'Gestão de activos físicos com excelência, eficiência e inovação.',
            ],
            // MANUTENCAO PREVENTIVA
            [
                'page_key' => 'panther-mat',
                'section_key' => 'manutencao',
                'content_key' => 'sec2_title',
                'label' => 'Título da Secção de Manutenção (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Manutenção Preventiva <br /><span class="text-gray-600 font-extrabold">e Corretiva Avançada</span>',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'manutencao',
                'content_key' => 'sec2_text_1',
                'label' => 'Texto da Secção de Manutenção - Parágrafo 1',
                'type' => 'textarea',
                'value' => 'Somos uma referência angolana no dimensionamento, instalação e manutenção preventiva de sistemas de climatização comercial (AVAC).',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'manutencao',
                'content_key' => 'sec2_text_2',
                'label' => 'Texto da Secção de Manutenção - Parágrafo 2',
                'type' => 'textarea',
                'value' => 'Disponibilização de piquetes técnicos urgentes para resolução rápida de falhas elétricas, inundações ou colapsos de climatização em Luanda. Garantimos suporte 24/7 para que o seu negócio não pare.',
            ],
            // PANTHERMAT SERVICE CARDS
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card1_image',
                'label' => 'Cartão 1 - Imagem',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card1_title',
                'label' => 'Cartão 1 - Título',
                'type' => 'text',
                'value' => 'Climatização AVAC',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card1_text',
                'label' => 'Cartão 1 - Descrição',
                'type' => 'textarea',
                'value' => 'Instalação de chillers, centrais de tratamento de ar (UTA) e cassetes de refrigeração comercial.',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card2_image',
                'label' => 'Cartão 2 - Imagem',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card2_title',
                'label' => 'Cartão 2 - Título',
                'type' => 'text',
                'value' => 'Facility Management',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card2_text',
                'label' => 'Cartão 2 - Descrição',
                'type' => 'textarea',
                'value' => 'Gestão física de condomínios comerciais, equipas residentes de eletricidade e canalização.',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card3_image',
                'label' => 'Cartão 3 - Imagem',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card3_title',
                'label' => 'Cartão 3 - Título',
                'type' => 'text',
                'value' => 'Otimização Energética',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card3_text',
                'label' => 'Cartão 3 - Descrição',
                'type' => 'textarea',
                'value' => 'Instalação de variadores de velocidade e condensadores de fator de potência.',
            ],
            // PANTHERMAT SPLIT SECTION
            [
                'page_key' => 'panther-mat',
                'section_key' => 'seccao_qualidade',
                'content_key' => 'split_image',
                'label' => 'Imagem de Fundo Lateral',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'seccao_qualidade',
                'content_key' => 'split_title',
                'label' => 'Título do Bloco (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Compromisso com a <br /><span class="text-gray-600 font-extrabold">Qualidade e Eficiência</span>',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'seccao_qualidade',
                'content_key' => 'split_text_1',
                'label' => 'Parágrafo 1',
                'type' => 'textarea',
                'value' => 'A nossa abordagem foca-se em reduzir custos operacionais enquanto aumentamos a longevidade dos equipamentos. Com técnicos altamente experientes, a PantherMAT transforma a manutenção de um centro de custos para um fator de vantagem competitiva.',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'seccao_qualidade',
                'content_key' => 'split_text_2',
                'label' => 'Parágrafo 2',
                'type' => 'textarea',
                'value' => 'Implementamos processos rigorosos de controlo e auditoria, permitindo antever falhas através de planos de manutenção preventiva detalhados.',
            ],
            // PANTHERMAT NOSSOS PROJECTOS
            [
                'page_key' => 'panther-mat',
                'section_key' => 'nossos_projectos',
                'content_key' => 'projects_title',
                'label' => 'Nossos Projectos - Título (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Projectos que reflectem a nossa <br /><span class="text-[#3b4b8a]">experiência, qualidade e compromisso</span>',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'nossos_projectos',
                'content_key' => 'projects_subtitle',
                'label' => 'Nossos Projectos - Subtítulo',
                'type' => 'textarea',
                'value' => 'Conheça em detalhe algumas das nossas obras estruturais de referência desenvolvidas para clientes nacionais e internacionais.',
            ],

            // PANTHEROIL PAGE
            [
                'page_key' => 'panther-oil',
                'section_key' => 'body',
                'content_key' => 'intro_image',
                'label' => 'Imagem Lateral da Introdução',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'body',
                'content_key' => 'description',
                'label' => 'Descrição Principal do Serviço (Parágrafo 1)',
                'type' => 'textarea',
                'value' => 'A PantherOIL garante serviços logísticos de resposta rápida e distribuição de consumíveis industriais homologados para bases petrolíferas nacionais.',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'body',
                'content_key' => 'intro_title',
                'label' => 'Título de Introdução (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Fornecemos suporte técnico <br class="hidden lg:block" /> operacional e logístico',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'body',
                'content_key' => 'description_2',
                'label' => 'Descrição Principal do Serviço (Parágrafo 2)',
                'type' => 'textarea',
                'value' => 'Com rigorosos padrões de saúde, segurança e ambiente (HSE), garantimos fornecimentos em tempo recorde e o suporte de engenheiros experientes.',
            ],
            // APOIO OFFSHORE
            [
                'page_key' => 'panther-oil',
                'section_key' => 'apoio_offshore',
                'content_key' => 'apoio_title',
                'label' => 'Título Apoio Offshore (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Distribuição e <br /><span class="text-[#cc1f26] font-extrabold">Apoio Offshore Especializado</span>',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'apoio_offshore',
                'content_key' => 'apoio_text_1',
                'label' => 'Texto Apoio Offshore - Parágrafo 1',
                'type' => 'textarea',
                'value' => 'Auditorias periódicas de tubulações, testes de estanqueidade e planos de contenção em conformidade com as normas regulamentares angolanas.',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'apoio_offshore',
                'content_key' => 'apoio_text_2',
                'label' => 'Texto Apoio Offshore - Parágrafo 2',
                'type' => 'textarea',
                'value' => 'Desempenhamos serviços logísticos avançados e suporte mecânico de engenharia diretamente em plataformas flutuantes e embarcações técnicas.',
            ],
            // PANTHEROIL NOSSOS PROJECTOS
            [
                'page_key' => 'panther-oil',
                'section_key' => 'nossos_projectos',
                'content_key' => 'projects_title',
                'label' => 'Nossos Projectos - Título (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Logística de Válvulas e <br />Apoio Técnico a Gasodutos',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'nossos_projectos',
                'content_key' => 'projects_subtitle',
                'label' => 'Nossos Projectos - Subtítulo',
                'type' => 'textarea',
                'value' => 'Conheça em detalhe alguns dos nossos projetos de referência no sector petrolífero.',
            ],
            // PLANOS DE CONTENCAO ECOLOGICA
            [
                'page_key' => 'panther-oil',
                'section_key' => 'planos_contencao',
                'content_key' => 'contencao_image',
                'label' => 'Imagem de Fundo Lateral',
                'type' => 'image',
                'value' => 'https://epcmholdings.com/wp-content/uploads/2024/09/Figure-1.-Inauguration-of-Plataforma.jpg',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'planos_contencao',
                'content_key' => 'contencao_title',
                'label' => 'Título da Caixa Vermelha',
                'type' => 'textarea',
                'value' => 'Planos de Contenção Ecológica e Monitorização',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'planos_contencao',
                'content_key' => 'contencao_text_1',
                'label' => 'Texto da Caixa Vermelha - Parágrafo 1',
                'type' => 'textarea',
                'value' => 'Desenho e teste prático de sistemas de segurança e estanqueidade para reservatórios de combustíveis.',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'planos_contencao',
                'content_key' => 'contencao_text_2',
                'label' => 'Texto da Caixa Vermelha - Parágrafo 2',
                'type' => 'textarea',
                'value' => 'Equipamentos mecânicos de vanguarda que respondem a protocolos rigorosos e fornecimento sem interrupções.',
            ],
            // SEGURANCA E RIGOR
            [
                'page_key' => 'panther-oil',
                'section_key' => 'seguranca',
                'content_key' => 'seguranca_title',
                'label' => 'Título da Secção de Segurança (Suporta HTML)',
                'type' => 'textarea',
                'value' => 'Segurança e Rigor <br /><span class="text-[#cc1f26]">Acima de Tudo</span>',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'seguranca',
                'content_key' => 'seguranca_text_1',
                'label' => 'Texto de Segurança - Parágrafo 1',
                'type' => 'textarea',
                'value' => 'A nossa política de saúde e segurança fomenta operações de excelência.',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'seguranca',
                'content_key' => 'seguranca_text_2',
                'label' => 'Texto de Segurança - Parágrafo 2',
                'type' => 'textarea',
                'value' => 'Temos orgulho no nosso percurso zero incidentes em projetos de grande complexidade técnica no setor petrolífero e de gás em Angola.',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'seguranca',
                'content_key' => 'seguranca_image',
                'label' => 'Imagem da Secção de Segurança',
                'type' => 'image',
                'value' => 'https://www.shell.co.uk/about-us/what-we-do/oil-and-gas/_jcr_content/root/main/section/item_394575230.shellimg.jpeg',
            ],

            // ENVIRO PAGE
            [
                'page_key' => 'enviro',
                'section_key' => 'body',
                'content_key' => 'description',
                'label' => 'Descrição Principal do Serviço',
                'type' => 'textarea',
                'value' => 'A Enviro.AO ajuda marcas líderes e indústrias nacionais a gerir a sua pegada ecológica através de auditorias e processos certificados de mitigação. Oferecemos consultoria ambiental completa para licenciamento, estudos de impacto e gestão integrada de resíduos.',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'body',
                'content_key' => 'intro_title',
                'label' => 'Título de Introdução (Suporta HTML)',
                'type' => 'textarea',
                'value' => '<span class="text-[#3b6b35] block">Líderes em Engenharia e</span><span class="text-[#99c24d] block">Consultoria Ambiental em Angola</span>',
            ],
            // ENVIRO CARDS GRID
            [
                'page_key' => 'enviro',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card1_title',
                'label' => 'Cartão 1 - Título',
                'type' => 'text',
                'value' => 'Licenciamento Ambiental',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card1_text',
                'label' => 'Cartão 1 - Descrição',
                'type' => 'textarea',
                'value' => 'Auditorias técnicas de conformidade e obtenção de licenças de operação ambiental.',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card2_title',
                'label' => 'Cartão 2 - Título',
                'type' => 'text',
                'value' => 'Gestão de Resíduos',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card2_text',
                'label' => 'Cartão 2 - Descrição',
                'type' => 'textarea',
                'value' => 'Processos certificados de recolha, tratamento e descarte ecológico de resíduos industriais.',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card3_title',
                'label' => 'Cartão 3 - Título',
                'type' => 'text',
                'value' => 'Estudos de Impacto',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'cartoes_servicos',
                'content_key' => 'card3_text',
                'label' => 'Cartão 3 - Descrição',
                'type' => 'textarea',
                'value' => 'Elaboração de estudos de impacto ambiental e social para grandes empreendimentos.',
            ],
            // ENVIRO TEXT + COLLAGE
            [
                'page_key' => 'enviro',
                'section_key' => 'colagem_texto',
                'content_key' => 'collage_title',
                'label' => 'Título do Bloco (Suporta HTML)',
                'type' => 'textarea',
                'value' => '<span class="text-[#3b6b35] block">Engenharia Sustentável</span><span class="text-[#99c24d] block">para o Futuro de Angola</span>',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'colagem_texto',
                'content_key' => 'collage_text_1',
                'label' => 'Parágrafo 1',
                'type' => 'textarea',
                'value' => 'A Enviro.AO desenvolve estratégias integradas que alinham os objetivos de crescimento económico com a preservação dos recursos naturais e biodiversidade local.',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'colagem_texto',
                'content_key' => 'collage_text_2',
                'label' => 'Parágrafo 2',
                'type' => 'textarea',
                'value' => 'As nossas equipas multidisciplinares de biólogos, engenheiros ambientais e consultores de sustentabilidade trabalham em parceria com órgãos governamentais.',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'colagem_texto',
                'content_key' => 'collage_img_1',
                'label' => 'Imagem da Colagem 1 (Superior)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'colagem_texto',
                'content_key' => 'collage_img_2',
                'label' => 'Imagem da Colagem 2 (Central)',
                'type' => 'image',
                'value' => 'https://www.endiama.co.ao/images/sustentavel/ambiental/img-03.webp',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'colagem_texto',
                'content_key' => 'collage_img_3',
                'label' => 'Imagem da Colagem 3 (Inferior)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
            ],
            // ENVIRO PARALLAX
            [
                'page_key' => 'enviro',
                'section_key' => 'parallax',
                'content_key' => 'parallax_image',
                'label' => 'Imagem de Fundo Parallax',
                'type' => 'image',
                'value' => 'https://images.ecycle.com.br/wp-content/uploads/2022/03/18132456/pexels-tom-fisk-2739666-scaled.jpg.webp',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'parallax',
                'content_key' => 'parallax_title',
                'label' => 'Título Parallax',
                'type' => 'textarea',
                'value' => 'Soluções Ecológicas com Rigor Técnico e Conformidade',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'parallax',
                'content_key' => 'parallax_text',
                'label' => 'Texto Parallax',
                'type' => 'textarea',
                'value' => 'Garantimos processos rigorosos de auditoria para mitigar riscos ambientais e promover práticas industriais sustentáveis.',
            ],
            // ENVIRO NOSSOS PROJECTOS
            [
                'page_key' => 'enviro',
                'section_key' => 'nossos_projectos',
                'content_key' => 'projects_title',
                'label' => 'Nossos Projectos - Título (Suporta HTML)',
                'type' => 'textarea',
                'value' => '<span class="text-[#3b6b35]">Projectos que reflectem a nossa</span><br><span class="text-[#9DBD4D]">experiência, qualidade e compromisso</span>',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'nossos_projectos',
                'content_key' => 'projects_subtitle',
                'label' => 'Nossos Projectos - Subtítulo',
                'type' => 'textarea',
                'value' => 'Conheça os nossos principais projetos de conservação ambiental e estudos de impacto executados em Angola.',
            ],
            // ENVIRO GRID 2X2
            [
                'page_key' => 'enviro',
                'section_key' => 'grid_2x2',
                'content_key' => 'grid1_title',
                'label' => 'Bloco 1 - Título',
                'type' => 'text',
                'value' => 'Preservação da Biodiversidade',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'grid_2x2',
                'content_key' => 'grid1_text',
                'label' => 'Bloco 1 - Texto',
                'type' => 'textarea',
                'value' => 'Desenvolvimento de programas de monitorização de fauna e flora em ecossistemas sensíveis.',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'grid_2x2',
                'content_key' => 'grid1_image',
                'label' => 'Bloco 1 - Imagem (Elefantes)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'grid_2x2',
                'content_key' => 'grid2_image',
                'label' => 'Bloco 2 - Imagem (Voluntários)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'grid_2x2',
                'content_key' => 'grid2_title',
                'label' => 'Bloco 2 - Título',
                'type' => 'text',
                'value' => 'Reflorestação Urbana',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'grid_2x2',
                'content_key' => 'grid2_text',
                'label' => 'Bloco 2 - Texto',
                'type' => 'textarea',
                'value' => 'Ações comunitárias e industriais para o plantio de árvores nativas em áreas degradadas.',
            ],

            // CERTIFICACOES PAGE
            [
                'page_key' => 'certificacoes',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner',
                'type' => 'text',
                'value' => 'Certificações do Grupo',
            ],
            [
                'page_key' => 'certificacoes',
                'section_key' => 'body',
                'content_key' => 'intro_text',
                'label' => 'Texto de Introdução',
                'type' => 'textarea',
                'value' => 'Garantimos a conformidade com as normas internacionais ISO em todos os estaleiros e bases de serviço do grupo, assegurando um ambiente laboral de risco zero.',
            ],

            // SUSTENTABILIDADE PAGE
            [
                'page_key' => 'sustentabilidade',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner',
                'type' => 'text',
                'value' => 'Sustentabilidade e ESG',
            ],
            [
                'page_key' => 'sustentabilidade',
                'section_key' => 'body',
                'content_key' => 'esg_text',
                'label' => 'Diretivas de Sustentabilidade',
                'type' => 'textarea',
                'value' => 'Reduzimos as emissões operacionais, implementamos energia solar distribuída em escritórios e realizamos acções regulares de reflorestação.',
            ],

            // PRIVACY PAGE
            [
                'page_key' => 'politica-de-privacidade',
                'section_key' => 'hero',
                'content_key' => 'hero_title',
                'label' => 'Título do Banner',
                'type' => 'text',
                'value' => 'Política de Privacidade',
            ],
            [
                'page_key' => 'politica-de-privacidade',
                'section_key' => 'body',
                'content_key' => 'content',
                'label' => 'Conteúdo Principal da Política',
                'type' => 'rich_text',
                'value' => '<p>O ABP Group respeita a sua privacidade. Recolhemos dados apenas para fins administrativos de contacto e processamento de candidaturas a emprego, garantindo a sua confidencialidade.</p><h3>Recolha de Informação</h3><p>Os seus dados são guardados de forma segura na nossa base de dados encriptada e nunca serão transmitidos a terceiros alheios ao grupo.</p>',
            ],
            // HOME STATS
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat1_number',
                'label' => 'Estatística 1 - Número/Valor',
                'type' => 'text',
                'value' => '+10',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat1_text',
                'label' => 'Estatística 1 - Texto descritivo',
                'type' => 'text',
                'value' => 'Anos de experiência consolidada no mercado de Angola.',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat2_number',
                'label' => 'Estatística 2 - Número/Valor',
                'type' => 'text',
                'value' => '+150',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat2_text',
                'label' => 'Estatística 2 - Texto descritivo',
                'type' => 'text',
                'value' => 'Projectos civis e industriais executados com excelência.',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat3_number',
                'label' => 'Estatística 3 - Número/Valor',
                'type' => 'text',
                'value' => '450',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat3_text',
                'label' => 'Estatística 3 - Texto descritivo',
                'type' => 'text',
                'value' => 'Profissionais qualificados nas equipas operacionais.',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat4_number',
                'label' => 'Estatística 4 - Número/Valor',
                'type' => 'text',
                'value' => '4',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat4_text',
                'label' => 'Estatística 4 - Texto descritivo',
                'type' => 'text',
                'value' => 'Unidades de negócio integradas e complementares.',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat5_number',
                'label' => 'Estatística 5 - Número/Valor',
                'type' => 'text',
                'value' => '18',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'stats',
                'content_key' => 'stat5_text',
                'label' => 'Estatística 5 - Texto descritivo',
                'type' => 'text',
                'value' => 'Províncias cobertas com serviços de infraestruturas.',
            ],
            // HOME SOLUTIONS INTRO
            [
                'page_key' => 'home',
                'section_key' => 'solutions',
                'content_key' => 'solutions_title_red',
                'label' => 'Secção Soluções - Título Destaque (Vermelho)',
                'type' => 'text',
                'value' => 'Soluções',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'solutions',
                'content_key' => 'solutions_title_blue',
                'label' => 'Secção Soluções - Título (Azul)',
                'type' => 'text',
                'value' => 'industriais integradas',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'solutions',
                'content_key' => 'solutions_vision',
                'label' => 'Secção Soluções - Texto de Visão/Destaque',
                'type' => 'textarea',
                'value' => 'A nossa visão — ser o principal parceiro na execução de projectos complexos e sustentáveis de energia, engenharia e ambiente em Angola.',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'solutions',
                'content_key' => 'solutions_desc',
                'label' => 'Secção Soluções - Descrição Detalhada',
                'type' => 'textarea',
                'value' => 'A excelência operacional e o rigor na segurança são os fundamentos de todas as nossas intervenções. Colaboramos estreitamente com os nossos clientes e parceiros para ir além do convencional, superando desafios técnicos e logísticos e implementando soluções que acrescentam valor real e promovem o desenvolvimento industrial do país.',
            ],
            // HOME CLIENTS INTRO
            [
                'page_key' => 'home',
                'section_key' => 'clients',
                'content_key' => 'clients_label',
                'label' => 'Secção Clientes - Rótulo/Etiqueta (Vermelho)',
                'type' => 'text',
                'value' => 'CLIENTES',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'clients',
                'content_key' => 'clients_title',
                'label' => 'Secção Clientes - Título principal',
                'type' => 'textarea',
                'value' => 'Parcerias estratégicas que reforçam a nossa capacidade de entrega',
            ],
            // HOME SUSTAINABILITY
            [
                'page_key' => 'home',
                'section_key' => 'sustainability',
                'content_key' => 'sustainability_title',
                'label' => 'Banner Verde - Título principal',
                'type' => 'text',
                'value' => 'Comprometidos com um Futuro Mais Sustentável',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'sustainability',
                'content_key' => 'sustainability_desc',
                'label' => 'Banner Verde - Texto descritivo',
                'type' => 'textarea',
                'value' => 'Desenvolvemos as nossas actividades com responsabilidade, promovendo práticas sustentáveis que geram valor para as comunidades, protegem o ambiente e contribuem para o desenvolvimento das gerações futuras.',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'sustainability',
                'content_key' => 'sustainability_image',
                'label' => 'Banner Verde - Imagem de Fundo (Floresta)',
                'type' => 'image',
                'value' => 'images/forest-canopy.png',
            ],
            // HOME NEWS INTRO
            [
                'page_key' => 'home',
                'section_key' => 'news',
                'content_key' => 'news_label',
                'label' => 'Secção Notícias - Rótulo/Etiqueta (Vermelho)',
                'type' => 'text',
                'value' => 'NÓTICIAS E EVENTOS',
            ],
            [
                'page_key' => 'home',
                'section_key' => 'news',
                'content_key' => 'news_title',
                'label' => 'Secção Notícias - Título principal',
                'type' => 'textarea',
                'value' => 'Acompanhe as nossas últimas actualizações e iniciativas',
            ],
            // HERO IMAGES FOR ALL PAGES
            [
                'page_key' => 'home',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'images/home-hero-new.png',
            ],
            [
                'page_key' => 'about',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
            [
                'page_key' => 'services',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'images/corporate-hero.png',
            ],
            [
                'page_key' => 'contact',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'images/corporate-hero.png',
            ],
            [
                'page_key' => 'panther-build',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'https://www.betar.pt/cms/wp-content/uploads/2021/12/Sky_Geral_0_TD-1.jpg',
            ],
            [
                'page_key' => 'panther-mat',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
            [
                'page_key' => 'panther-oil',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1605389601633-911e3b5e43a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
            [
                'page_key' => 'enviro',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero (Fallback do Vídeo)',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
            [
                'page_key' => 'certificacoes',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1556155092-490a1ba16284?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
            [
                'page_key' => 'sustentabilidade',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
            [
                'page_key' => 'politica-de-privacidade',
                'section_key' => 'hero',
                'content_key' => 'hero_image',
                'label' => 'Imagem de Fundo do Hero',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1450101499163-c8848c66cb85?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80',
            ],
        ];

        foreach ($contents as $content) {
            PageContent::create($content);
        }
    }
}
